# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

$PROVISIONSCRIPT = <<SCRIPT

sudo echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update -y
sudo apt-get install apt-transport-https -y 
sudo apt-get install postgresql-$2 -y

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.hostname = "postgres"
	config.vm.box = "ubuntu/trusty64"
	config.vbguest.auto_update = true
	config.vbguest.no_remote = false
  
	config.vm.provider :virtualbox do |vbox|
		vbox.memory = 512
		vbox.cpus = 2
		vbox.name="postgres"
	end
	
	config.vm.network  "private_network", ip: vagrant_config['private_ip']
	config.vm.network "forwarded_port", guest: 5432, host: 5432, protocol: "tcp"
	
	config.vm.provision "shell" do |s|
		s.inline = $PROVISIONSCRIPT
		s.args = [vagrant_config['private_ip'], vagrant_config['postgres_version'] ]
	end
	
end
