# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

$PROVISIONSCRIPT = <<SCRIPT

mkdir /vagrant/data
mkdir /vagrant/data/log
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 -y
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/$2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-$2.list
sudo apt-get update
sudo apt-get install apt-transport-https mongodb-org -y

sudo service mongod stop
sudo usermod -G vagrant mongodb

#sudo mv /var/lib/mongodb/ /vagrant/data
#sudo sed -i -e 's/dbPath: \\\/var\\\/lib\\\/mongodb/dbPath: \\\/vagrant\\\/data\\\/mongodb/g' /etc/mongod.conf
#sudo sed -i -e 's/path: \\\/var\\\/log\\\/mongodb\\\/mongod.log/path: \\\/vagrant\\\/data\\\/log\\\/mongod.log/g' /etc/mongod.conf

sudo service mongod start

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.hostname = "mongodb"
	config.vm.box = "ubuntu/trusty64"
	config.vbguest.auto_update = true
	config.vbguest.no_remote = false
  
	config.vm.provider :virtualbox do |vbox|
		vbox.memory = 512
		vbox.cpus = 2
		vbox.name="mongodb"
	end
	
	config.vm.network  "private_network", ip: vagrant_config['private_ip']
	config.vm.network "forwarded_port", guest: 27017, host: 27017, protocol: "tcp"
	
	config.vm.provision "shell" do |s|
		s.inline = $PROVISIONSCRIPT
		s.args = [vagrant_config['private_ip'], vagrant_config['mongo_version'] ]
	end
	
end
